class Amazon::PrimeVideo::ScarpService < BaseScarpingService
  def self.call(initial_page = nil)
    initial_page ||= '/gp/video/search/ref=atv_mv_hom_1_c_0djxkw_4_smr?queryToken=eyJ0eXBlIjoicXVlcnkiLCJuYXYiOnRydWUsInBpIjoiZGVmYXVsdCIsInNlYyI6ImNlbnRlciIsInN0eXBlIjoic2VhcmNoIiwicXJ5Ijoibm9kZT0yODU4Nzc4MDExJmZpZWxkLXdheXNfdG9fd2F0Y2g9MTIwMDc4NjUwMTEmcF9uX2VudGl0eV90eXBlPTE0MDY5MTg0MDExJmFkdWx0LXByb2R1Y3Q9MCZzZWFyY2gtYWxpYXM9aW5zdGFudC12aWRlbyZiYm49Mjg1ODc3ODAxMSZxcy1hdl9yZXF1ZXN0X3R5cGU9NCZxcy1pcy1wcmltZS1jdXN0b21lcj0wIiwicnQiOiIwZEpYS1dzbXIiLCJ0eHQiOiJQb3B1bGFyIG1vdmllcyIsInN1YnR4dCI6IkluY2x1ZGVkIHdpdGggUHJpbWUiLCJvZmZzZXQiOjAsIm5wc2kiOjAsIm9yZXEiOiIzNjc0OTQ3YS0zOTgzLTQ3YjMtODhmZi1lYzQwNDRjNzZhNzU6MTU5NzA1NDMyODAwMCIsInN0cmlkIjoiMToxMlNHS1MwQzFEMkxTVCMjTVpRV0daTFVNVlNFR1lMU041MlhHWkxNIiwib3JlcWsiOiJMaTYrby9nc2gwaEdDY1RnYVRnS0x6bWJBenR6bmdvc29lSTA2emFoZmRJPSIsIm9yZXFrdiI6MX0%3D&pageId=default&queryPageType=browse&ie=UTF8'

    Amazon::PrimeVideo::PageParseWorker.perform_async(initial_page)
  end
end
